---
apiVersion: v1
kind: Service
metadata:
  name: mvp-fluxcd-app
  namespace: mvp-fluxcd-app
spec:
  type: ClusterIP
  selector:
    app: mvp-fluxcd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
